#!/usr/bin/env bash
# sync-docs.sh — keep the GENERATED doc sections in sync with the filesystem.
#
# Regenerates two marker-delimited regions so they always reflect what exists:
#   README.md   <!-- prism:commands --> ... <!-- /prism:commands -->   (one row per commands/*.md)
#   OVERVIEW.md <!-- prism:docs --> ... <!-- /prism:docs -->           (one row per docs/*)
#
# It does NOT write prose. Narrative (the article, hand-curated tables) stays human, by design:
# a script that auto-writes prose produces slop. This only syncs the deterministic indexes.
#
# Usage:
#   bash scripts/sync-docs.sh          # rewrite the regions in place
#   bash scripts/sync-docs.sh --check  # exit 1 if a region is stale (for the pre-commit hook / CI)

set -uo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

CHECK=0
[ "${1:-}" = "--check" ] && CHECK=1

tmpd=$(mktemp -d)
trap 'rm -rf "$tmpd"' EXIT

# --- generate the command index (from commands/*.md and skills/*/SKILL.md frontmatter) ---
# Every user-invocable capability lands here. Skills also fire model-invoked, so they carry a tag.
cmds="$tmpd/cmds.md"
rows="$tmpd/cmd-rows.md"
: > "$rows"
count=0
for f in commands/*.md; do
  [ -e "$f" ] || continue
  name="/$(basename "$f" .md)"
  desc=$(grep -m1 '^description:' "$f" | sed 's/^description:[[:space:]]*//')
  printf -- '- `%s`: %s\n' "$name" "$desc" >> "$rows"
  count=$((count + 1))
done
for f in skills/*/SKILL.md; do
  [ -e "$f" ] || continue
  name="/$(basename "$(dirname "$f")")"
  desc=$(grep -m1 '^description:' "$f" | sed 's/^description:[[:space:]]*//')
  printf -- '- `%s` _(skill — also auto-invoked)_: %s\n' "$name" "$desc" >> "$rows"
  count=$((count + 1))
done
sort "$rows" > "$cmds"
printf '\n_%s commands and skills. Auto-generated by `scripts/sync-docs.sh`; do not edit by hand._\n' "$count" >> "$cmds"

# --- generate the docs index (from docs/*) ---
docs="$tmpd/docs.md"
: > "$docs"
shopt -s nullglob
for f in docs/*; do
  [ -f "$f" ] || continue
  case "$f" in
    *.md)   title=$(grep -m1 '^# ' "$f" | sed 's/^#[[:space:]]*//') ;;
    *.html) title=$(grep -m1 -o '<title>[^<]*</title>' "$f" | sed 's/<[^>]*>//g') ;;
    *)      title="" ;;
  esac
  printf -- '- [`%s`](%s)%s\n' "$(basename "$f")" "$f" "${title:+: $title}" >> "$docs"
done
printf '\n_Auto-generated by `scripts/sync-docs.sh`; do not edit by hand._\n' >> "$docs"

# --- replace one marked region in a file with a content file ---
fill_region() {
  local file="$1" tag="$2" content="$3"
  awk -v start="<!-- prism:$tag -->" -v end="<!-- /prism:$tag -->" -v cf="$content" '
    BEGIN { buf=""; while ((getline line < cf) > 0) buf = buf line "\n" }
    {
      if ($0 == start) { print; printf "%s", buf; skip=1; next }
      if ($0 == end)   { skip=0; print; next }
      if (!skip) print
    }
  ' "$file" > "$file.synctmp" && mv "$file.synctmp" "$file"
}

# --- sync one file, honoring --check ---
sync_file() {
  local file="$1" tag="$2" content="$3"
  if ! grep -q "<!-- prism:$tag -->" "$file"; then
    echo "WARN: $file has no <!-- prism:$tag --> region; skipping." >&2
    return 0
  fi
  cp "$file" "$tmpd/before"
  fill_region "$file" "$tag" "$content"
  if diff -q "$tmpd/before" "$file" >/dev/null; then
    return 0
  fi
  if [ "$CHECK" = "1" ]; then
    mv "$tmpd/before" "$file"   # restore; --check must not modify
    echo "DRIFT: $file ($tag) is stale; run: bash scripts/sync-docs.sh"
    return 1
  fi
  echo "updated: $file ($tag)"
  return 0
}

rc=0
sync_file README.md   commands "$cmds" || rc=1
sync_file OVERVIEW.md docs     "$docs" || rc=1
exit $rc
